import { MenuItem, Order } from '@/src/types';

export const INITIAL_MENU: MenuItem[] = [
  {
    id: 'bk-1',
    name: 'Seared Scallops',
    description: 'Brewed tea or coffee, orange juice, freshly baked croissant, danish, bread rolls and toast, butter and jams, cereal, muesli, yogurt, cheeses, eggs cooked your way, fresh fruits, bacon, sausages, potato, tomato, and mushrooms.',
    price: 6.000,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1533089862017-ec329abb0a29?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-2',
    name: 'Mediterranean Breakfast',
    description: 'Brewed tea or coffee, orange juice, freshly baked pastries with honey, jam and butter, hummus, white cheese, labneh, tomato, cucumber, olives and pickles, cold cuts, foul, boiled eggs, falafel, and eggs cooked your way.',
    price: 5.500,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-3',
    name: 'Eggs',
    description: 'Eggs cooked your way served with beef bacon, chicken sausages, potatoes, peppers, tomatoes, and mushroom.',
    price: 2.000,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414395d8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-4',
    name: 'Cheese Plate',
    description: 'A selection of international cheeses served with a freshly baked bread basket.',
    price: 3.000,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-5',
    name: 'Pastry Basket',
    description: 'Croissant, assorted Danish, and cinnamon roll.',
    price: 2.750,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-6',
    name: 'Baguette',
    description: 'Freshly baked baguette.',
    price: 1.100,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1598373182133-52452f7691ef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-7',
    name: 'Kraft Corn Loaf',
    description: 'Freshly baked corn loaf.',
    price: 1.250,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-8',
    name: 'Multi Cereal Loaf',
    description: 'Healthy multi-cereal loaf.',
    price: 1.250,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-9',
    name: 'Country Loaf',
    description: 'Classic country style loaf.',
    price: 1.250,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-10',
    name: 'Pancakes & Waffles',
    description: 'Choose between pancakes or waffles with either maple syrup, strawberries or chocolate sauce and fruits.',
    price: 3.500,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-11',
    name: 'Cereal',
    description: 'Your choice of cornflakes, rice krispies, all bran or muesli. Served with cold or hot milk.',
    price: 1.750,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1521483450421-a0589197e595?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bk-12',
    name: 'Fresh Fruits',
    description: 'A platter of fresh cut seasonal fruits.',
    price: 1.500,
    category: 'Breakfast',
    menuType: 'Breakfast',
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '1',
    name: 'Seared Scallops',
    description: 'Pan-seared atlantic scallops served with a lemon butter sauce and microgreens.',
    price: 24,
    category: 'Appetizers',
    menuType: 'All Day',
    isAvailable: true,
    imageUrl: 'https://picsum.photos/400/300?random=1',
  },
  {
    id: '2',
    name: 'Lobster Thermidor',
    description: 'Fresh lobster meat cooked in a rich wine sauce, stuffed back into the shell and browned.',
    price: 58,
    category: 'Main Course',
    menuType: 'All Day',
    isAvailable: true,
    imageUrl: 'https://picsum.photos/400/300?random=2',
  },
  {
    id: '3',
    name: 'Truffle Mushroom Risotto',
    description: 'Creamy arborio rice with wild mushrooms, parmesan, and shaved black truffle.',
    price: 32,
    category: 'Risotto',
    menuType: 'All Day',
    isAvailable: true,
    imageUrl: 'https://picsum.photos/400/300?random=3',
  },
  {
    id: '4',
    name: 'Coconut Panna Cotta',
    description: 'Silky coconut cream set with agar, topped with mango coulis and toasted flakes.',
    price: 14,
    category: 'Sweets and Fruits',
    menuType: 'All Day',
    isAvailable: true,
    imageUrl: 'https://picsum.photos/400/300?random=4',
  },
  {
    id: '5',
    name: 'Signature Mojito',
    description: 'White rum, sugar, lime juice, soda water, and fresh mint.',
    price: 16,
    category: 'Cocktails',
    menuType: 'All Day',
    isAvailable: true,
    imageUrl: 'https://picsum.photos/400/300?random=5',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-123',
    guestName: 'Mr. Thompson',
    roomNumber: '104',
    items: [
      { itemId: '1', name: 'Seared Scallops', quantity: 1, price: 24 },
      { itemId: '2', name: 'Lobster Thermidor', quantity: 1, price: 58 },
    ],
    status: 'pending',
    totalAmount: 82,
    createdAt: Date.now() - 1000 * 60 * 5, // 5 mins ago
  },
  {
    id: 'ord-124',
    guestName: 'Sarah Jenks',
    roomNumber: '201',
    items: [
      { itemId: '5', name: 'Signature Mojito', quantity: 2, price: 16 },
    ],
    status: 'preparing',
    totalAmount: 32,
    createdAt: Date.now() - 1000 * 60 * 15, // 15 mins ago
  },
  {
    id: 'ord-125',
    guestName: 'Family Room',
    roomNumber: 'Villa 3',
    items: [
      { itemId: '3', name: 'Truffle Mushroom Risotto', quantity: 2, price: 32 },
      { itemId: '4', name: 'Coconut Panna Cotta', quantity: 2, price: 14 },
    ],
    status: 'ready',
    totalAmount: 92,
    createdAt: Date.now() - 1000 * 60 * 30, // 30 mins ago
  },
];

export const CATEGORIES = [
  'Breakfast',
  'Hot Beverages',
  'Frappes',
  'Smoothies',
  'Milkshakes',
  'Hot Chocolates',
  'Fresh Juices',
  'Specialty Coffee',
  'Cold Beverages',
  'Cocktails',
  'Malt Beverages',
  'Refreshing Drinks',
  'Appetizers',
  'Italian Pasta',
  'Soups',
  'Salads',
  'Risotto',
  'Pizzeria Chez Nous',
  'Main Course',
  'Sweets and Fruits'
];
